<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>creditCard_charge</name>
   <tag></tag>
   <elementGuidId>de4ffcfb-cbf4-4052-abe0-45b5d1b86f09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;d-none d-md-block&quot;]/div[contains(text(),&quot;Your credit card will be charged&quot;)]/span/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '126.30' or . = '126.30')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18a0afb8-0c58-4b22-aa62-bea6eb7cbcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold </value>
      <webElementGuid>cc056290-c3b0-4442-bd1d-5f27858b3331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>126.30</value>
      <webElementGuid>52899b1d-c53e-4cf8-9f00-e1e4177f2839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/main[@class=&quot;CheckoutPage theme-light&quot;]/div[@class=&quot;full-site-width&quot;]/section[@class=&quot;Section pb-sm-3 pb-md-0&quot;]/div[@class=&quot;row theme-light-content&quot;]/div[@class=&quot;col-md-7 px-lg-5 py-sm-5 mb-3 mb-md-0&quot;]/div[@class=&quot;d-none d-md-block&quot;]/div[@class=&quot;my-4&quot;]/span[1]/span[@class=&quot;font-weight-bold&quot;]</value>
      <webElementGuid>84693809-38df-475a-b579-1dcbad757621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/main/div[3]/section/div/div/div[6]/div/span/span</value>
      <webElementGuid>e706061a-ea46-411a-a36a-acb33bcb8b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[4]/following::span[1]</value>
      <webElementGuid>66f0728b-ff11-4492-b5c0-2877b1ca1ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place pickup order'])[1]/preceding::span[1]</value>
      <webElementGuid>4c30e256-2874-41b7-9a8c-6638e0c0705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::span[2]</value>
      <webElementGuid>a13c5fad-adfd-4d84-ab71-f36b13535bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='126.30']/parent::*</value>
      <webElementGuid>4323dc16-63dc-4c6d-aca6-1f3e6816725e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/span</value>
      <webElementGuid>a1275351-dcdb-49f6-a6dc-35f3de853be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '126.30' or . = '126.30')]</value>
      <webElementGuid>525d02fc-16bf-45ac-be64-32689e072e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
